language: java
before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sftwnd_crayfish_common_expectation -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization="sftwnd-github" -Dsonar.sourceEncoding=UTF-8
jdk: openjdk11
os: linux
